# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 签到薅羊毛

on:
  schedule:
    # 此处是UTC时间，对应北京时间早八点
    - cron : '05 08 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
        # spec: 'daily_sign.py'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run daily_sign
      run: |
        python daily_sign.py
      env:
        JD_COOKIE: ${{ secrets.JD_COOKIE }}
